-- file: 10-create-user-and-db.sql
CREATE DATABASE persons;
CREATE ROLE program WITH PASSWORD 'test';
GRANT ALL PRIVILEGES ON DATABASE persons TO program;
ALTER ROLE program WITH LOGIN;

CREATE TABLE persons (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(1023) NOT NULL,
    work_name VARCHAR(4095) DEFAULT NULL,
    addr VARCHAR(4095) DEFAULT NULL,
    age INT DEFAULT NULL
);
